// import React from 'react'

const Contact = () => {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio officiis dolore minus inventore qui ducimus minima adipisci nulla quidem, quo voluptas sequi facere, incidunt, dignissimos rem quasi quibusdam aspernatur eligendi explicabo molestias laborum dolorum debitis ad! Aperiam quam reiciendis quo minima vitae dolor saepe, odit nemo numquam assumenda culpa optio nihil vel quisquam illum? Eius iure quis nam obcaecati nemo debitis, natus architecto odio adipisci incidunt fuga, temporibus ut, voluptatem assumenda eaque explicabo totam error. Ab fuga doloribus distinctio commodi id dolor adipisci, perferendis quibusdam harum ipsa quos magnam amet repellendus quaerat expedita minus praesentium debitis soluta quasi temporibus veniam quis possimus. Atque esse nesciunt quae, perferendis asperiores quisquam illum reiciendis officiis nemo, hic tenetur beatae provident! Suscipit, magni! Voluptates incidunt totam fugit. Accusamus laborum sint laudantium? Officiis temporibus explicabo deleniti ab asperiores, impedit, ut libero repellat, ducimus laboriosam autem quidem. Ea odit velit saepe facilis architecto perspiciatis incidunt libero iste aperiam, nulla aut, odio officia in beatae? Ad dolores maiores, laborum ut nobis similique! Distinctio laborum dolor necessitatibus beatae ab eveniet libero? Possimus consequatur necessitatibus quibusdam magni quam, voluptate, ad ab modi dolorum dignissimos ratione eligendi qui iusto. Accusamus qui esse laudantium est voluptate doloribus ducimus ad, quos perferendis porro, unde architecto ipsa cupiditate, atque sequi quis cumque odit ipsum a provident. Aliquam ratione repellat, laudantium perspiciatis numquam saepe quidem ducimus temporibus provident harum commodi. Libero ipsam accusantium nesciunt voluptatibus ratione eligendi excepturi provident est nam? At suscipit facere tenetur incidunt, aut nihil unde vel sapiente tempore error quas, laboriosam sed omnis porro, sequi dolorem distinctio eaque nemo nam animi illum recusandae dignissimos! Qui architecto asperiores alias, nemo nobis dolorem, porro ratione cupiditate necessitatibus harum exercitationem atque, pariatur fuga vero aspernatur debitis doloremque consequuntur officia iure praesentium est officiis? Odio est asperiores molestias ipsum sapiente ab, tenetur iusto. Dolore.</p>
    </div>
  )
}

export default Contact
